### ISSUE TITLE
Add example metadata.yml and document supported types

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/cookiecutter-osparc-service#106]
**USER STORY:**
A user of the cookiecutter came back with this question:

Is there a list of valid input data types, and the options (default, max, min etc) for each one? The one I am having trouble with is taking a list of numbers, like the 4th input in the webinar example at timestamp 19:07.

**DEFINITION OF DONE:**

```[tasklist]
### Tasks
- [ ] Document all the types we support @pcrespov 
- [ ] Add an example metadata file with more advanced examples than files (e.g. the ascent runner is a good use-case) @elisabettai 
- [ ] Add link to json-form playground so users can test
```

**Comment by pcrespov** [comment]
@elisabettai I need more input here. Perhaps we can meet offline and clarify some points ?
